### ISSUE TITLE
Delete Shopping Item

### ISSUE THREAD

**Issue by natush2** [natush2/shopping-buddy#4]
# Delete Shopping Item

## Value Proposition

**As a user**

**I want to** remove items that I no longer need,

**so that** I can keep my shopping list up-to-date and relevant.

## Description

Capstone Student Todo: Add wireframes

## Acceptance Criteria

- Each shopping item in the shopping list includes an easily accessible delete option.
- Clicking the delete option triggers a confirmation dialog.
- The dialog serves to prevent accidental deletions by asking the user to confirm their intention.
- The dialog includes options for both confirming the deletion and cancelling the action.
- The cancellation option allows the user to back out of the deletion process if selected by mistake or if they change their mind.
- Upon confirming the deletion, the item is removed from the shopping list.
- If all shopping items are deleted, a message appears indicating that there are no shopping items and providing an option to add new ones.

## Tasks

- [ ] Create feature branch `feature/delete-shopping-item`
- [ ] Capstone Student Todo: Add tasks

**Comment by JessicaLoers** [comment]
📒 Handout/Link List
[react-state-3: Updating Arrays of Objects in State / removing an object](https://github.com/neuefische/hh-web-24-3/blob/main/sessions/react-state-3/react-state-3.md#removing-an-object)

**Comment by natush2** [comment]
### Видалення товару з покупок

#### Пропозиція цінності
Як користувач,

я хочу видалити товари, які більше не потрібні,

щоб я міг підтримувати свій список покупок актуальним та релевантним.

#### Опис
Туду для студента-курсового: Додати wireframes

#### Критерії прийняття
1. Кожен товар у списку покупок має легко доступну опцію видалення.
2. Натискання на опцію видалення викликає діалог підтвердження.
3. Діалог служить для запобігання випадковому видаленню, запитуючи у користувача підтвердження його наміру.
4. Діалог включає опції для підтвердження видалення та скасування дії.
5. Опція скасування дозволяє користувачу відмовитися від процесу видалення, якщо вибрана помилково або якщо змінюється думка.
6. Після підтвердження видалення товару, він видаляється зі списку покупок.
7. Якщо всі товари в списку покупок видалено, з'являється повідомлення про відсутність товарів у списку з можливістю додати нові.

#### Завдання
1. Створити функціональну гілку `feature/delete-shopping-item`
2. Туду для студента-курсового: Додати завдання
