### ISSUE TITLE
Filter Shopping Items

### ISSUE THREAD

**Issue by natush2** [natush2/shopping-buddy#7]
# Filter Shopping Items

## Value Proposition

**As a user**

**I want to** filter shopping items by category,

**so that** I can easily find specific items in my list.

## Description

Capstone Student Todo: Add wireframes

## Acceptance Criteria

- The shopping list includes a section with filter options.
- Users can filter shopping items by category.
- A dropdown menu or a set of radio buttons is available, allowing users to select a category from the existing categories list.
- Users can only select one category at a time.
- Selecting a new category automatically deselects the previously selected category.
- The applied filter is clearly displayed on the shopping list, allowing users to see which filter is currently active.
- Users can clear the applied filter with a single click, returning the list to its unfiltered state.
- The shopping list updates in real-time when a category is selected, showing only items belonging to the chosen category.
- If no shopping items match the selected filter criteria, a message is displayed indicating that no shopping items were found.
- The filter interface is intuitive and easy to use, ensuring that new users can easily understand how to apply and clear filters.

## Tasks

- [ ] Create feature branch `feature/filter-shopping-items`
- [ ] Capstone Student Todo: Add tasks

**Comment by JessicaLoers** [comment]
📒 Handout/Link List
[React Documentation](https://react.dev/learn/rendering-lists#filtering-arrays-of-items) Filter Arrays of items

**Comment by natush2** [comment]
**Фільтрація елементів списку покупок**

**Ціннісна пропозиція**
Як користувач,  
я хочу фільтрувати елементи списку покупок за категоріями,  
щоб легко знаходити конкретні елементи у своєму списку.

**Опис**
Capstone студент повинен додати вайрфрейми.

**Критерії прийняття**
- Список покупок містить секцію з опціями фільтрації.
- Користувачі можуть фільтрувати елементи списку покупок за категоріями.
- Доступне випадаюче меню або набір радіокнопок, які дозволяють користувачам обирати категорію зі списку існуючих категорій.
- Користувачі можуть обирати лише одну категорію одночасно.
- Вибір нової категорії автоматично знімає вибір попередньої категорії.
- Застосований фільтр чітко відображається у списку покупок, що дозволяє користувачам бачити, який фільтр наразі активний.
- Користувачі можуть очистити застосований фільтр одним кліком, повертаючи список до нефільтрованого стану.
- Список покупок оновлюється в реальному часі після вибору категорії, відображаючи лише елементи, що належать до вибраної категорії.
- Якщо жоден елемент списку покупок не відповідає вибраним критеріям фільтрації, відображається повідомлення про те, що елементи не знайдено.
- Інтерфейс фільтрації інтуїтивно зрозумілий і легкий у використанні, забезпечуючи можливість новим користувачам легко зрозуміти, як застосовувати та очищати фільтри.

**Завдання**
- Створити гілку feature/filter-shopping-items.
- Capstone студент повинен додати завдання.
